### ISSUE TITLE
Please handle properly wrong trace files

### ISSUE THREAD

**Issue by jirka-h** [jirvoz/plot-nr-running#11]
Hi!

Recently, I have run into trace files with this content:

$more lu.C.x_254_NORMAL_TRACE_2.trace
File possibly truncated. Need at least 188747342217323, but file size is 5498483.

plot-nr-running.py failes with trace log on this line:

cpus_count = int(input_file.readline().split('=')[1])

Please handle this situation properly. Add try block around this line and give error message that the input file is in an unexpected format. 

Thanks!
Jirka

**Comment by jirka-h** [comment]
plot-nr-running.py --lscpu=lscpu.txt --image-file ./lu.C.x_132_NORMAL_TRACE_2.trace.png ./lu.C.x_132_NORMAL_TRACE_2.trace.xz > ./lu.C.x_132_NORMAL_TRACE_2.trace.log                                     
Traceback (most recent call last):
  File "/home/jhladky/GIT/plot-nr-running/plot-nr-running.py", line 254, in <module>
    args.duration, args.image_file, numa_cpus)
  File "/home/jhladky/GIT/plot-nr-running/plot-nr-running.py", line 149, in process_report
    cpus_count = int(input_file.readline().split('=')[1])
IndexError: list index out of range

**Comment by jirvoz** [comment]
Fixed in commit d83d7a6.
